apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-search.fullname" . }}-settings
  labels:
    {{- include "private-search.labels" . | nindent 4 }}
data:
  settings.yml: |-
    {{- toYaml .Values.settings | nindent 4 }}
