{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "private-search.fullname" . }}-secret
  labels:
    {{- include "private-search.labels" . | nindent 4 }}
type: Opaque
data:
  searchKey: {{ .Values.secret.key | b64enc }}
{{- end}}
