name: Helm Package

on:
  push:
    tags:
      - "*"

permissions:
  packages: write

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.2.0
        id: install

      - name: Set chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{  github.ref_name }}"' 'config.yml'

      - name: Build and Push
        run: |
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io/codayblue
          helm package ${{ github.workspace }}/chart
          CHART_TO_UPLOAD=$(find ${{ github.workspace}} -name '*.tgz')
          helm push ${CHART_TO_UPLOAD} oci://ghcr.io/codayblue
